config/routes.rb
SampleApp::Application.routes.draw do

  get "microposts/create"
  get "microposts/destroy"
  resources :users do
    member do
      get :following, :followers
    end
    resources :lists, only: [:create, :destroy, :show, :index] do
      get :members
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :list_memberships, only: [:create, :destroy]
  resources :list_subscriptions, only: [:create, :destroy]
  root 'static_pages#home'
  match 'help',    to: 'static_pages#help',    via: 'get'
  match 'about',   to: 'static_pages#about',   via: 'get'
  match 'contact', to: 'static_pages#contact', via: 'get'

  match 'signup',  to: 'users#new',            via: 'get'
  match 'signin',  to: 'sessions#new',         via: 'get'
  match 'signout', to: 'sessions#destroy',     via: 'delete'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_list_left_pane.html.erb
<aside class="span4">
  <section>
    <h1><%= @list.name %></h1>
    <span>A list by <%= link_to @list.user.name, @list.user %></span>
  </section>
  <section>
    <% @user ||= current_user %>
    <div class="stats">
      <a href="<%= user_list_path(@list.user, @list) %>">
        <strong id="posts" class="stat">
          Posts
        </strong>
      </a>
      <a href="<%= user_list_members_path(@list.user, @list) %>">
        <strong id="members" class="stat">
          Members
        </strong>
      </a>
    </div>
  </section>
  <section>
    <%= render 'subscription_form' %>
  </section>
</aside>

app/views/shared/_list_members.html.erb
<% if !current_user?(@user) && @lists.any? %>
  <button type="button"
          class="btn btn-info"
          data-toggle="modal"
          data-target="#membershipContainer">
          Add or remove from list
  </button>

  <div id="membershipContainer" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Include <%= @user.name %> in</h4>
        </div>

        <div id="list_lists" class="modal-body">
          <%= render 'shared/list_members_partial' %>
        </div>

      </div>
    </div>
  </div>

  <script type="text/javascript">
  $(document.body).on('change', ".list_membership", function() {
    if (this.checked) {
      $.ajax({
        url: '/list_memberships',
        type: 'POST',
        data: { "list_membership": {
          list_id: $(this).attr('list_id'),
          user_id: <%= @user.id %>
        }}
      });
      console.log("Triggering listener...2");
      $.ajax({
        url: '/list_memberships/' + this.value,
        type: 'DELETE'
      });
    }
  });
  </script>
<% end %>

app/views/shared/_list_members_partial.html.erb
<% @lists.each do |list| %>
  <div class="checkbox">
    <label>
      <%= check_box_tag "list_#{list.id}",
                        @memberships[list.id],
                        @memberships.key?(list.id),
                        class: 'list_membership',
                        list_id: list.id %>
      <%= list.name %>
    </label>
  </div>
<% end %>

app/views/shared/_list_mini.html.erb
<li>
  <span><%= link_to list_mini.name, user_list_path(@user, list_mini) %></span>
  <% unless list_mini.description.blank? %>
    <span><%= list_mini.description %></span>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_mini_profile.html.erb
<%= gravatar_for @user %>
<h1><%= @user.name %></h1>
<span><%= link_to "view my profile", @user %></span>
<span><b>Microposts:</b> <%= @user.microposts.count %></span>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <a href="<%= user_lists_path(@user) %>">
    <strong id="lists" class="stat">
      <%= @user.lists.count %>
    </strong>
    <%= "list".pluralize(@user.lists.count) %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>